### ISSUE TITLE
 Team-Work

### ISSUE THREAD

**Issue by muharremyesilyurt** [bounswe/bounswe2016group3#3]
**The need of producing software engineers with strong teamwork has been repeatedly stressed by industry worldwide. ABET includes this skill among the essential ones needed to be mastered by the students of an accredited program.**

**Comment by muharremyesilyurt** [comment]
Software engineering is largely based on group work.Because it increases the quality of output, morale and retention.Also there are some risks to working alone that affect output quality and morale:

- Working alone reduces learning.
- Working on a team increases the bus factor for a project. The bus factor refers the number of team members can be hit by a bus; for example gets sick or leaves the company, before a project comes to a complete halt. A higher bus factor reduces risk on a project.
- Working on a team increases accountability. If you are working with people you should do your task on time.
- The lows of a project are more demoralizing when working alone.
- The highs of a project are more motivating when working as a team. To boost morale you can celebrate an achievement with teammates.If you dont have a group you need someone to celebrate it :)
- The lower morale from solo projects also tends to mean lower employee happiness and consequently lower retention.

And there are [15 Quotes to Inspire Great Teamwork](http://www.inc.com/dave-kerpen/15-quotes-to-inspire-great-team-work.html)
(My favourite is "None of us is as smart as all of us." --Ken Blanchard.)

For all those reasons engineers should work in a group.

**Comment by osmannnurikar** [comment]
[What if God was one of us?](https://www.youtube.com/watch?v=B4CRkpBGQzU) :)

**Comment by menafkasap** [comment]
[Morgan is that you?](https://www.youtube.com/watch?v=FngXOUxklR4)

**Comment by NoorAhmd** [comment]
Working effectively as part of a team is incredibly important for output quality, morale, and retention.
From the perspective of efficiency, a traditional argument against staffing large teams comes from Frederick Brooks’s The Mythical Man-Month. A man-month or person-month refers to the unit of work that one person can accomplish in one month. The basic premise that Brooks argues against is the notion that a software project that takes one person a year to complete (twelve person-months) can have its timeline shortened to a single month simply by staffing the project with a dozen engineers. Upon seeing projects falling behind, many managers want to put schedules back on track by simply adding more engineers to the project.
The problem with this logic — and the reason it’s a myth — is that each additional engineer added to a project incurs both communication and coordination overhead with everyone else on the team, and so the time to complete a project doesn’t actually decrease linearly with increased staffing. 
Because of this line of reasoning, managers or technical leads sometimes over-correct and attempt to maximize efficiency by staffing single-person projects to reduce the communication overhead down to zero. Some companies, like Google, even emphasize in their promotion processes that an engineer has to demonstrate ownership in a project, which incentivizes engineers to define and prioritize individual projects so that they can be the indisputable owners of those projects and increase their chances for a promotion.

The reality is that there are a number of downsides and risks to working alone that affect output quality and moral.
